//
export enum ESPlayerInterceptorType {
  //
  ES_PLAYER_INTERCEPTOR_TYPE_DEFAULT = 0,
  //播放视频
  ES_PLAYER_INTERCEPTOR_TYPE_MEDIA_ITEM_LIST = 1,
  //播放分集
  ES_PLAYER_INTERCEPTOR_TYPE_MEDIA_ITEM = 2,
  //播放地址合集
  ES_PLAYER_INTERCEPTOR_TYPE_MEDIA_SOURCE_LIST = 3,
  //播放地址
  ES_PLAYER_INTERCEPTOR_TYPE_MEDIA_SOURCE = 4,
  //播放地址合集
  ES_PLAYER_INTERCEPTOR_TYPE_AD_MEDIA_SOURCE_LIST = 5,
  //播放地址
  ES_PLAYER_INTERCEPTOR_TYPE_AD_MEDIA_SOURCE = 6,
}
