export enum ESPlayerAspectRatio {
  ES_PLAYER_AR_ASPECT_FIT_PARENT = 0,//等比全屏
  ES_PLAYER_AR_ASPECT_FILL_PARENT = 1,
  ES_PLAYER_AR_ASPECT_WRAP_CONTENT = 2,//1:1
  ES_PLAYER_AR_ASPECT_MATCH_PARENT = 3,//全屏
  ES_PLAYER_AR_16_9_FIT_PARENT = 4,//16:9
  ES_PLAYER_AR_4_3_FIT_PARENT = 5,//4:3
  ES_PLAYER_AR_235_FIT_PARENT = 6,
}
