export enum ESPlayerState {
  ES_PLAYER_STATE_IDLE = 0,//初始化完成
  ES_PLAYER_STATE_PREPARING = 1,//正在准备
  ES_PLAYER_STATE_PREPARED = 2,//准备完毕
  ES_PLAYER_STATE_BUFFER_START = 3,//正在缓冲
  ES_PLAYER_STATE_BUFFER_END = 4,//正在缓冲
  ES_PLAYER_STATE_PLAYING = 5,//正在播放
  ES_PLAYER_STATE_SEEK_START = 6,//快进开始
  ES_PLAYER_STATE_SEEK_COMPLETED = 7,//快进完成
  ES_PLAYER_STATE_PAUSED = 8,//暂停
  ES_PLAYER_STATE_RESUMED = 9,//继续播放
  ES_PLAYER_STATE_BEFORE_STOP = 10,//停止之前
  ES_PLAYER_STATE_STOP = 11,//停止
  ES_PLAYER_STATE_PLAYBACK_COMPLETED = 12,//播放完毕
  ES_PLAYER_STATE_ERROR = 13,//错误
  ES_PLAYER_STATE_VIDEO_SIZE_CHANGED = 14,//视频尺寸变化
  ES_PLAYER_STATE_PLAYER_VIEW_CHANGED = 15,//播放布局变化

  ES_PLAYER_STATE_AD_START = 16,//广告开始
  ES_PLAYER_STATE_AD_END = 17,//广告结束
  ES_PLAYER_STATE_AD_SKIP = 18,//广告跳过
  ES_PLAYER_STATE_AD_PAUSED = 19,//广告暂停


  //鉴权通过，tvbc播放器鉴权
  ES_PLAYER_STATE_AUTHORIZED = 20,
  //设置播放倍速成功
  ES_PLAYER_STATE_SET_PLAY_RATE_SUCCESS = 21,
  //设置播放倍速报错
  ES_PLAYER_STATE_SET_PLAY_RATE_ERROR = 22,

  //广告
  ES_PLAYER_STATE_AD_RESUMED = 23,//广告RESUME
  ES_PLAYER_STATE_AD_LOADED = 24,
  ES_PLAYER_STATE_AD_TIME = 25,//广告倒计时时间

  ES_PLAYER_STATE_PLAYER_INITIALIZED = 26,//播放器初始化完毕
  ES_PLAYER_STATE_TIMED_TEXT_CHANGED = 27,
  //
  ES_PLAYER_STATE_PLAYER_CLICKABLE = 28,//播放器view是否可以点击

  //初始化
  ES_PLAYER_STATE_INITIALIZE_SUCCESS = 29,//初始化成功
  ES_PLAYER_STATE_INITIALIZE_ERROR = 30,//初始化错误

}
