export enum ESAudioDurationHint {
  ES_AUDIO_FOCUS_NONE = 0,
  ES_AUDIO_FOCUS_GAIN = 1,
  ES_AUDIO_FOCUS_GAIN_TRANSIENT = 2,
  ES_AUDIO_FOCUS_GAIN_TRANSIENT_MAY_DUCK = 3,
  ES_AUDIO_FOCUS_GAIN_TRANSIENT_EXCLUSIVE = 4,
}
