export enum ESAudioManagerFlag {
  ES_AUDIO_MANAGER_FLAG_SHOW_UI = 1 << 0,
  ES_AUDIO_MANAGER_FLAG_ALLOW_RINGER_MODES = 1 << 1,
  ES_AUDIO_MANAGER_FLAG_PLAY_SOUND = 1 << 2,
  ES_AUDIO_MANAGER_FLAG_REMOVE_SOUND_AND_VIBRATE = 1 << 3,
  ES_AUDIO_MANAGER_FLAG_VIBRATE = 1 << 4,
  ES_AUDIO_MANAGER_FLAG_FIXED_VOLUME = 1 << 5,
  ES_AUDIO_MANAGER_FLAG_BLUETOOTH_ABS_VOLUME = 1 << 6,
  ES_AUDIO_MANAGER_FLAG_SHOW_SILENT_HINT = 1 << 7,
  ES_AUDIO_MANAGER_FLAG_HDMI_SYSTEM_AUDIO_VOLUME = 1 << 8,
  ES_AUDIO_MANAGER_FLAG_ACTIVE_MEDIA_ONLY = 1 << 9,
  ES_AUDIO_MANAGER_FLAG_SHOW_UI_WARNINGS = 1 << 10,
  ES_AUDIO_MANAGER_FLAG_SHOW_VIBRATE_HINT = 1 << 11,
}
