//
export enum ESKeyCode {
  ES_KEYCODE_ENTER = 66,
  ES_KEYCODE_DPAD_CENTER = 23,
  ES_KEYCODE_DPAD_UP = 19,
  ES_KEYCODE_DPAD_DOWN = 20,
  ES_KEYCODE_DPAD_LEFT = 21,
  ES_KEYCODE_DPAD_RIGHT = 22,
  ES_KEYCODE_BACK = 4,
  ES_KEYCODE_ESCAPE = 111,
  ES_KEYCODE_MENU = 82,
  ES_KEYCODE_SEARCH = 84,
  ES_KEYCODE_F12 = 142,
  ES_KEYCODE_BACKSLASH = 73,
}
