//
export enum ESPlayerDefinitionStrategy {
  ES_PLAYER_DEFINITION_STRATEGY_NONE = -1,//默认一直播放最高清
  ES_PLAYER_DEFINITION_STRATEGY_HIGHEST = 0,//默认一直播放最高清
  ES_PLAYER_DEFINITION_STRATEGY_LOWEST = 1,//默认一直播放最低
  ES_PLAYER_DEFINITION_STRATEGY_MEDIUM = 2,//中间的清晰度
//
  ES_PLAYER_DEFINITION_STRATEGY_SPECIFIED_LOWER = 3,//指定的清晰度，如果没有则，选择由低到高选择
  ES_PLAYER_DEFINITION_STRATEGY_SPECIFIED_HIGHER = 4,//指定的清晰度，如果没有则，由高到低选择
  ES_PLAYER_DEFINITION_STRATEGY_SPECIFIED_LOWEST = 5,//指定的清晰度，如果没有则，选择最低
  ES_PLAYER_DEFINITION_STRATEGY_SPECIFIED_HIGHEST = 6,//指定的清晰度，如果没有则，选择最高
}
