//
export enum ESNativeRouterLaunchMode {
  ES_NATIVE_ROUTER_LAUNCH_MODE_CLEAR_TASK = 1,
  ES_NATIVE_ROUTER_LAUNCH_MODE_SINGLE_TASK = 2,
  ES_NATIVE_ROUTER_LAUNCH_MODE_SINGLE_TOP = 4,
  ES_NATIVE_ROUTER_LAUNCH_MODE_SINGLE_INSTANCE = 8,
}
