/**
 *
 */
export enum ESPlayerOptionType {
  ES_PLAYER_OPTION_TYPE_INT = 0,
  ES_PLAYER_OPTION_TYPE_STRING = 1,
}

export enum ESPlayerOptionCategory {
  ES_PLAYER_OPTION_CATEGORY_FORMAT = 1,
  ES_PLAYER_OPTION_CATEGORY_CODEC = 2,
  ES_PLAYER_OPTION_CATEGORY_SWS = 3,
  ES_PLAYER_OPTION_CATEGORY_PLAYER = 4,
}
