export enum ESNetworkInfoState {
  ES_NETWORK_INFO_STATE_CONNECTING = 0,
  ES_NETWORK_INFO_STATE_CONNECTED = 1,
  ES_NETWORK_INFO_STATE_SUSPENDED = 2,
  ES_NETWORK_INFO_STATE_DISCONNECTING = 3,
  ES_NETWORK_INFO_STATE_DISCONNECTED = 4,
  ES_NETWORK_INFO_STATE_UNKNOWN = 5,
}
