export enum ESSharedDataType {
  ES_SHARED_DATA_TYPE_INT = 0,
  ES_SHARED_DATA_TYPE_LONG = 1,
  ES_SHARED_DATA_TYPE_FLOAT = 2,
  ES_SHARED_DATA_TYPE_STRING = 3,
  ES_SHARED_DATA_TYPE_BOOLEAN = 4,
  ES_SHARED_DATA_TYPE_MAP = 5,
  ES_SHARED_DATA_TYPE_ARRAY = 6,
}
