/**
 *
 */
export enum ESBuiltinADPlayerType {
  ES_BUILTIN_PLAYER_TYPE_UNKNOWN = -1,//未知
  ES_BUILTIN_PLAYER_TYPE_PREVIOUS_ROLL_AD = 1,//前贴
  ES_BUILTIN_PLAYER_TYPE_MIDDLE_ROLL_AD = 2,//暂停
  ES_BUILTIN_PLAYER_TYPE_POST_ROLL_AD = 4,//后贴
}
