export enum ESSoundPoolContentType {
  ES_SOUND_POOL_CONTENT_TYPE_UNKNOWN = 0,
  ES_SOUND_POOL_CONTENT_TYPE_SPEECH = 1,
  ES_SOUND_POOL_CONTENT_TYPE_MUSIC = 2,
  ES_SOUND_POOL_CONTENT_TYPE_MOVIE = 3,
  ES_SOUND_POOL_CONTENT_TYPE_SONIFICATION = 4,
}
