export enum ESDownloadState {
  ES_DOWNLOAD_STATE_INIT = 0,
  ES_DOWNLOAD_STATE_START = 1,
  ES_DOWNLOAD_STATE_PROGRESS = 2,
  ES_DOWNLOAD_STATE_STOP = 3,
  ES_DOWNLOAD_STATE_CANCEL = 4,
  ES_DOWNLOAD_STATE_SUCCESS = 5,
  ES_DOWNLOAD_STATE_ERROR = 6
}
